name: Docker Image Publish
on:
  push:
    branches: [master]
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 19
      - run: mvn clean install --batch-mode --errors --fail-at-end
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: github-cicd-actions-0.0.1-SNAPSHOT.jar
          path: target/
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Retrieve saved jar
        uses: actions/download-artifact@v2
        with:
            name: github-cicd-actions-0.0.1-SNAPSHOT.jar
            path: target/
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Image
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: |
          
          docker login --username $username --password $password ghcr.io
          docker build . --tag ghcr.io/riyaknol11/cicd-gke-deployment:latest
          docker push ghcr.io/riyaknol11/cicd-gke-deployment:latest
      - name: Deploy to GKE
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/

